# Generated by Django 3.1.6 on 2021-02-19 03:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('porto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortoPage',
            new_name='PortoIndexPage',
        ),
    ]
