# Generated by Django 3.1.6 on 2021-02-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0002_auto_20210219_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='overview',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
